### ISSUE TITLE
sample requests

### ISSUE THREAD

**Issue by 0xling** [eset/stadeo#4]
I want to try stadeo by following your usage examples. Can you provide the sample from the usage_examples.pdf?
SHA-1 of the sample: 791ad58d9bb66ea08465aad4ea968656c81d0b8e

**Comment by nyx0** [comment]
Hello @0xling, please send us an email request to threatintel [at] eset [dot] com.
Thank you.

**Comment by nofiv** [comment]
Hi @0xling, thank you for reaching out to us. It turns out that we are allowed to share the samples here. I attach all of them for any future inquiries: [stadeo_samples.zip](https://github.com/eset/stadeo/files/7677921/stadeo_samples.zip).

**Comment by HuangZurong** [comment]
> Hi @0xling, thank you for reaching out to us. It turns out that we are allowed to share the samples here. I attach all of them for any future inquiries: [stadeo_samples.zip](https://github.com/eset/stadeo/files/7677921/stadeo_samples.zip).

Can you provide the unzip password for the zip file?

**Comment by nofiv** [comment]
Hi @HuangZurong, the password is `infected`.

**Comment by HuangZurong** [comment]
> Hi @HuangZurong, the password is `infected`.

Thanks .
